import React,{useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';
const products=[
{id:1,name:'Midnight Oud',cat:'Men',price:2499,note:'Oud · Amber · Spice',emoji:'🖤'},
{id:2,name:'Velvet Rose',cat:'Women',price:2199,note:'Rose · Vanilla · Musk',emoji:'🌹'},
{id:3,name:'Citrus Noir',cat:'Unisex',price:1999,note:'Bergamot · Cedar · Musk',emoji:'🍋'},
{id:4,name:'Royal Musk',cat:'Men',price:2799,note:'Musk · Leather · Wood',emoji:'👑'},
{id:5,name:'Bloom Élan',cat:'Women',price:2399,note:'Jasmine · Pear · Vanilla',emoji:'🌸'},
{id:6,name:'Sandal Mist',cat:'Unisex',price:1899,note:'Sandalwood · Iris · Amber',emoji:'✨'}];
function App(){const[cart,setCart]=useState([]),[page,setPage]=useState('shop'),[method,setMethod]=useState('cod'),[order,setOrder]=useState(null),[pay,setPay]=useState({phone:'',mpin:''});
const add=p=>setCart(c=>{let x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,q:i.q+1}:i):[...c,{...p,q:1}]});
const total=cart.reduce((s,i)=>s+i.price*i.q,0); const confirm=()=>{if(!cart.length)return alert('Your cart is empty.');if(method==='esewa'&&(!pay.phone||!pay.mpin))return alert('Enter demo eSewa number and MPIN.');setOrder('PF-'+Date.now().toString().slice(-8)+'-'+Math.floor(100+Math.random()*900));setPage('success');};
if(page==='success')return <main className="success"><div className="tick">✓</div><h1>Order Confirmed!</h1><p>Thank you for shopping at Sugandha.</p><div className="order">Order ID: <b>{order}</b></div><button onClick={()=>{setCart([]);setPage('shop')}}>Continue Shopping</button></main>;
return <><header><div className="logo">SUGANDHA <span>PERFUMES</span></div><nav><button onClick={()=>setPage('shop')}>Shop</button><button onClick={()=>setPage('cart')}>Cart ({cart.reduce((s,i)=>s+i.q,0)})</button></nav></header>
{page==='shop'?<><section className="hero"><div><small>THE ART OF FRAGRANCE</small><h1>Find your<br/><i>signature scent.</i></h1><p>Elegant fragrances crafted for unforgettable moments. Delivered across Nepal.</p><button onClick={()=>document.getElementById('products').scrollIntoView({behavior:'smooth'})}>Explore Collection</button></div><div className="bottle">S<br/><span>EAU DE PARFUM</span></div></section><section id="products"><div className="sectionTitle"><small>OUR COLLECTION</small><h2>Scents made to be remembered.</h2></div><div className="grid">{products.map(p=><article key={p.id}><div className="visual"><span>{p.emoji}</span><div className="miniBottle">S</div></div><small>{p.cat}</small><h3>{p.name}</h3><p>{p.note}</p><div className="buy"><b>Rs. {p.price.toLocaleString()}</b><button onClick={()=>add(p)}>Add +</button></div></article>)}</div></section></>:<main className="checkout"><h1>Your Bag</h1>{!cart.length?<p>Your cart is empty.</p>:<div className="columns"><section className="items">{cart.map(i=><div className="cartItem"><div className="thumb">{i.emoji}</div><div><b>{i.name}</b><p>Rs. {i.price.toLocaleString()} × {i.q}</p></div><button onClick={()=>setCart(c=>c.filter(x=>x.id!==i.id))}>Remove</button></div>)}</section><section className="panel"><h2>Checkout</h2><input placeholder="Full name"/><input placeholder="Phone number"/><input placeholder="Delivery address"/><h3>Payment</h3><label className={method==='cod'?'selected':''}><input type="radio" checked={method==='cod'} onChange={()=>setMethod('cod')}/> Cash on Delivery</label><label className={method==='esewa'?'selected':''}><input type="radio" checked={method==='esewa'} onChange={()=>setMethod('esewa')}/> eSewa Demo</label>{method==='esewa'&&<div className="esewa"><div className="eLogo">eSewa</div><p>Demo Checkout</p><input value={pay.phone} onChange={e=>setPay({...pay,phone:e.target.value})} placeholder="98XXXXXXXX"/><input value={pay.mpin} onChange={e=>setPay({...pay,mpin:e.target.value})} type="password" placeholder="Demo MPIN"/><small>This is a simulated payment. No real money is charged.</small></div>}<div className="total"><span>Total</span><b>Rs. {total.toLocaleString()}</b></div><button className="confirm" onClick={confirm}>Confirm Order</button></section></div>}</main>}
<footer>© 2026 Sugandha Perfumes · Demo Store</footer></>};createRoot(document.getElementById('root')).render(<App/>);
